openapi: 3.0.4
info:
  title: Password Strength
  description: >-
    Password Strength is a simple tool for checking the strength of a password.
    It returns the strength of the password based on various factors.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/passwordstrength:
    get:
      summary: Check Password Strength
      description: Check the strength of a password
      operationId: passwordstrength
      parameters:
        - name: password
          in: query
          schema:
            type: string
          required: true
          description: The password to check the strength of
          example: Password123
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  strength: weak
                  passwordInfo:
                    length: 11
                    hasSpecialCharacters: false
                    hasNumbers: true
                    hasLowercase: true
                    hasUppercase: true
                    hasSpaces: false
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
